In [4]:
List= ["spagetti", "pizza", "cheese cake"]

In [5]:
List

['spagetti', 'pizza', 'cheese cake']

In [6]:
List[2] #index starts with 0,1,2

'cheese cake'

In [7]:
list=["Rinat", 12, 3.86, List]

In [8]:
list

['Rinat', 12, 3.86, ['spagetti', 'pizza', 'cheese cake']]

In [63]:
list [2:5] #list slicing with value above the last index!

[3.86, ['spagetti', 'pizza', 'cheese cake', 'banana', 'avocado']]

In [10]:
lista=[1, 2, 3, 4]

In [11]:
lista

[1, 2, 3, 4]

In [12]:
lista [3:5]

[4]

In [13]:
List.extend(["banana", "avocado"]) #extend adds new elements

In [14]:
List

['spagetti', 'pizza', 'cheese cake', 'banana', 'avocado']

In [15]:
List.append ([1,2,3]) #append adds one element only, no matter how many elemnts are inside

In [16]:
List

['spagetti', 'pizza', 'cheese cake', 'banana', 'avocado', [1, 2, 3]]

In [28]:
#lists are mutabla = we can change them

In [17]:
del(List[5]) #del deletes an element

In [18]:
List

['spagetti', 'pizza', 'cheese cake', 'banana', 'avocado']

In [1]:
#split = We can convert a string to a list using split. For example, the method split translates every group of characters separated by a space into an element in a list

In [26]:
'cheese cake'.split()

['cheese', 'cake']

In [54]:
A= ["TV", 200, 0.5] #clone lists - examples:

In [55]:
A

['TV', 200, 0.5]

In [56]:
B = A

In [57]:
B

['TV', 200, 0.5]

In [58]:
print (A, B)

['TV', 200, 0.5] ['TV', 200, 0.5]

In [59]:
A[0] = "radio"

In [60]:
A

['radio', 200, 0.5]

In [61]:
print ('B[0]:', B[0])
A[0] = "radio"
print ('B[0]:', B[0])

B[0]: radio
B[0]: radio

In [62]:
B = A[:]
B
# another way to clone lists. In this way B will not change if A will change

['radio', 200, 0.5]

In [64]:
A = [1, "TRUE", 'b']
B = [100, "FALSE", 'd']
A+B
#concatenate lists = to unite

[1, 'TRUE', 'b', 100, 'FALSE', 'd']